# Generated by Django 6.0.5 on 2026-05-23 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('customer_type', models.CharField(choices=[('Wholesaler', 'Wholesaler'), ('Retailer', 'Retailer'), ('Walk-in', 'Walk-in')], max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='sales',
            name='customer_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='salesapp.customer'),
        ),
    ]
