# Generated by Django 6.0.5 on 2026-05-16 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salesapp', '0003_product_selling_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='category_name',
        ),
        migrations.RenameField(
            model_name='sales',
            old_name='product',
            new_name='product_name',
        ),
    ]
