# Generated by Django 6.0.5 on 2026-05-17 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesapp', '0004_rename_category_product_category_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='distance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
        migrations.AddField(
            model_name='sales',
            name='transport_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
        migrations.AddField(
            model_name='sales',
            name='transport_note',
            field=models.TextField(default=''),
        ),
    ]
