# Generated by Django 6.0.5 on 2026-05-20 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('salesapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(default=0)),
                ('unit_cost', models.IntegerField(default=0)),
                ('amount_paid', models.IntegerField(default=0)),
                ('selling_price', models.IntegerField(default=0)),
                ('date', models.DateField(auto_now_add=True)),
                ('is_paid', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salesapp.product')),
            ],
        ),
    ]
