# Generated by Django 6.0.5 on 2026-05-14 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='product',
            field=models.CharField(choices=[('cement', 'Cement'), ('iron_bars', 'iron_bars'), ('nails', 'nails'), ('roofings', 'roofings'), ('wheelbarrows', 'wheelbarrows'), ('mire mesh', 'mire mesh'), ('barbed wire', 'barbed wire')], default='cement', max_length=100),
        ),
    ]
