# Generated by Django 6.0.5 on 2026-05-14 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0002_alter_stock_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='amount_due',
        ),
        migrations.AlterField(
            model_name='stock',
            name='product',
            field=models.CharField(choices=[('cement', 'Cement'), ('iron_bars', 'iron_bars'), ('nails', 'nails'), ('roofings', 'roofings'), ('wheelbarrows', 'wheelbarrows'), ('wire mesh', 'wire mesh'), ('barbed wire', 'barbed wire')], default='cement', max_length=100),
        ),
    ]
