# Generated by Django 6.0.5 on 2026-05-14 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0003_remove_stock_amount_due_alter_stock_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='amount_paid',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stock',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stock',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stock',
            name='unit_cost',
            field=models.IntegerField(default=0),
        ),
    ]
