# Generated by Django 6.0.5 on 2026-05-14 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0004_alter_stock_amount_paid_alter_stock_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='price',
            field=models.IntegerField(),
        ),
    ]
