# Generated by Django 6.0.5 on 2026-05-14 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=100)),
                ('supplier', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('is_paid', models.BooleanField(default=True)),
                ('amount_paid', models.IntegerField()),
                ('amount_due', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('unit_cost', models.IntegerField()),
            ],
        ),
    ]
