# Generated by Django 6.0.5 on 2026-05-16 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesapp', '0004_rename_category_product_category_name_and_more'),
        ('stockapp', '0006_alter_stock_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='price',
            new_name='selling_price',
        ),
        migrations.AlterField(
            model_name='stock',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salesapp.product'),
        ),
    ]
