# Generated by Django 6.0.5 on 2026-05-23 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schemeapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schemecustomer',
            name='employer_name',
        ),
    ]
