# Generated by Django 6.0.5 on 2026-05-23 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemeapp', '0002_remove_schemecustomer_employer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='schemecustomer',
            name='Customer_type',
            field=models.CharField(choices=[('wholesaler', 'wholesaler'), ('retailer', 'retailer'), ('walk_in', 'walk_in')], default='walk_in ', max_length=20),
        ),
    ]
