# Generated by Django 6.0.5 on 2026-05-23 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemeapp', '0003_schemecustomer_customer_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schemecustomer',
            name='Customer_type',
            field=models.CharField(choices=[('wholesaler', 'wholesaler'), ('retailer', 'retailer'), ('walk_in', 'walk_in'), ('Deposit', 'Deposit')], default='Deposit ', max_length=20),
        ),
    ]
