# Generated by Django 6.0.5 on 2026-05-23 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schemeapp', '0004_alter_schemecustomer_customer_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schemecustomer',
            name='Customer_type',
        ),
    ]
